2021-11-06 20:57:32,844 DEBUG decos.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2021-11-06 20:57:32,846 DEBUG decos.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2021-11-06 20:57:32,855 DEBUG decos.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2021-11-06 20:57:32,856 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2021-11-06 20:57:32,857 DEBUG server.py Аргументы успешно загружены.
2021-11-06 20:57:33,008 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2021-11-06 20:57:44,113 INFO core.py Установлено соедение с ПК ('127.0.0.1', 63236)
2021-11-06 20:57:44,616 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1284, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 63236)>,) , {}. Вызов из модуля common.utils
2021-11-06 20:57:44,616 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1636221464.124518, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq4Ofqs/HQUMTJs+GRue8\nmy91MPTc5UF6QudJ0CR/A+T7hF/RRR9oGuHq00WovXMmotrOSk0fde1w8ibeAxBZ\nQwj5lL7dy2V2lgKF7xwZK5ubkPFN1fFUbFjBOgKe4GrpVIjgMWFXlTa2dq8WPMef\niVLLjS2i73005QNAqAQDpbIJ/yfH84lFBDlzK1HK9gOCuTI30hkvA5CeayFElvPT\nmOM7I0tBCHtmyyvNn2O3AtwO8Wk5AGuLjgt1nK2vDNHH8utA6uyJs5Use3fMjyE0\nWiOt8FqKuCS7EsM8tSHleqNqPjP8a6/kocNQ+r0eEEHmd9l8Ae7s1kJcenOoMyGx\ngwIDAQAB\n-----END PUBLIC KEY-----'}}
2021-11-06 20:57:44,616 DEBUG core.py Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq4Ofqs/HQUMTJs+GRue8\nmy91MPTc5UF6QudJ0CR/A+T7hF/RRR9oGuHq00WovXMmotrOSk0fde1w8ibeAxBZ\nQwj5lL7dy2V2lgKF7xwZK5ubkPFN1fFUbFjBOgKe4GrpVIjgMWFXlTa2dq8WPMef\niVLLjS2i73005QNAqAQDpbIJ/yfH84lFBDlzK1HK9gOCuTI30hkvA5CeayFElvPT\nmOM7I0tBCHtmyyvNn2O3AtwO8Wk5AGuLjgt1nK2vDNHH8utA6uyJs5Use3fMjyE0\nWiOt8FqKuCS7EsM8tSHleqNqPjP8a6/kocNQ+r0eEEHmd9l8Ae7s1kJcenOoMyGx\ngwIDAQAB\n-----END PUBLIC KEY-----'}
2021-11-06 20:57:44,660 DEBUG core.py Unknown username, sending {'response': 400, 'error': 'Пользователь не зарегистрирован.'}
2021-11-06 20:57:44,661 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=1284, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 63236)>, {'response': 400, 'error': 'Пользователь не зарегистрирован.'}) , {}. Вызов из модуля common.utils
2021-11-06 20:57:45,832 INFO core.py Установлено соедение с ПК ('127.0.0.1', 63237)
2021-11-06 20:57:46,335 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1284, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 63237)>,) , {}. Вызов из модуля common.utils
2021-11-06 20:57:46,336 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1636221465.8438034, 'user': {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl9aX0/sPgTHCLBGFh+mB\nQV2brPbZTZXrGu9pxfkxWhQJB/83c/fAFrRuSl2MaiNRG1mtj0wuFFgi5nLWx7q9\nJqdkyROvXeeFUr7NHCubIPj2e6utsgHLPGONVYOXPnwPgzD4r5Ehc+xpU6yBwom6\nxeEpoKEf1NLut+J09jkNWEiaiPGrZcUjIhrzBDoZUClQbFBSwctRk9K96qo9c2rA\nmAzKtg7k5yt8qNenQrEgCtHfwyQZ5vFu/nmUCtQ3rDfEf/S7DbkZ3U2AHeFfNR28\nC/46en4gTkyIKB3hKPKtt74PCv/1YVOew/OkMALPq/swwSI3ZMYcctS+LyNIr9cm\npQIDAQAB\n-----END PUBLIC KEY-----'}}
2021-11-06 20:57:46,336 DEBUG core.py Start auth process for {'account_name': 'test2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl9aX0/sPgTHCLBGFh+mB\nQV2brPbZTZXrGu9pxfkxWhQJB/83c/fAFrRuSl2MaiNRG1mtj0wuFFgi5nLWx7q9\nJqdkyROvXeeFUr7NHCubIPj2e6utsgHLPGONVYOXPnwPgzD4r5Ehc+xpU6yBwom6\nxeEpoKEf1NLut+J09jkNWEiaiPGrZcUjIhrzBDoZUClQbFBSwctRk9K96qo9c2rA\nmAzKtg7k5yt8qNenQrEgCtHfwyQZ5vFu/nmUCtQ3rDfEf/S7DbkZ3U2AHeFfNR28\nC/46en4gTkyIKB3hKPKtt74PCv/1YVOew/OkMALPq/swwSI3ZMYcctS+LyNIr9cm\npQIDAQAB\n-----END PUBLIC KEY-----'}
2021-11-06 20:57:46,339 DEBUG core.py Unknown username, sending {'response': 400, 'error': 'Пользователь не зарегистрирован.'}
2021-11-06 20:57:46,339 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=1284, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 63237)>, {'response': 400, 'error': 'Пользователь не зарегистрирован.'}) , {}. Вызов из модуля common.utils
2021-11-06 20:59:02,119 INFO core.py Установлено соедение с ПК ('127.0.0.1', 63241)
2021-11-06 20:59:02,632 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1244, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 63241)>,) , {}. Вызов из модуля common.utils
2021-11-06 20:59:02,633 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1636221542.1466503, 'user': {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq4Ofqs/HQUMTJs+GRue8\nmy91MPTc5UF6QudJ0CR/A+T7hF/RRR9oGuHq00WovXMmotrOSk0fde1w8ibeAxBZ\nQwj5lL7dy2V2lgKF7xwZK5ubkPFN1fFUbFjBOgKe4GrpVIjgMWFXlTa2dq8WPMef\niVLLjS2i73005QNAqAQDpbIJ/yfH84lFBDlzK1HK9gOCuTI30hkvA5CeayFElvPT\nmOM7I0tBCHtmyyvNn2O3AtwO8Wk5AGuLjgt1nK2vDNHH8utA6uyJs5Use3fMjyE0\nWiOt8FqKuCS7EsM8tSHleqNqPjP8a6/kocNQ+r0eEEHmd9l8Ae7s1kJcenOoMyGx\ngwIDAQAB\n-----END PUBLIC KEY-----'}}
2021-11-06 20:59:02,633 DEBUG core.py Start auth process for {'account_name': 'test1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq4Ofqs/HQUMTJs+GRue8\nmy91MPTc5UF6QudJ0CR/A+T7hF/RRR9oGuHq00WovXMmotrOSk0fde1w8ibeAxBZ\nQwj5lL7dy2V2lgKF7xwZK5ubkPFN1fFUbFjBOgKe4GrpVIjgMWFXlTa2dq8WPMef\niVLLjS2i73005QNAqAQDpbIJ/yfH84lFBDlzK1HK9gOCuTI30hkvA5CeayFElvPT\nmOM7I0tBCHtmyyvNn2O3AtwO8Wk5AGuLjgt1nK2vDNHH8utA6uyJs5Use3fMjyE0\nWiOt8FqKuCS7EsM8tSHleqNqPjP8a6/kocNQ+r0eEEHmd9l8Ae7s1kJcenOoMyGx\ngwIDAQAB\n-----END PUBLIC KEY-----'}
2021-11-06 20:59:02,637 DEBUG core.py Unknown username, sending {'response': 400, 'error': 'Пользователь не зарегистрирован.'}
2021-11-06 20:59:02,638 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=1244, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 63241)>, {'response': 400, 'error': 'Пользователь не зарегистрирован.'}) , {}. Вызов из модуля common.utils
