2021-11-02 19:31:29,960 DEBUG decos.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2021-11-02 19:31:29,973 DEBUG decos.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2021-11-02 19:31:29,991 DEBUG decos.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2021-11-02 19:31:29,991 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['server.py']
2021-11-02 19:31:29,994 DEBUG server.py Аргументы успешно загружены.
2021-11-02 19:31:30,096 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2021-11-02 19:31:52,626 DEBUG decos.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2021-11-02 19:31:52,626 DEBUG decos.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2021-11-02 19:31:52,627 DEBUG decos.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2021-11-02 19:31:52,627 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['C:/Users/Максар/Desktop/geekbrains/PYQT/project/server.py']
2021-11-02 19:31:52,628 DEBUG server.py Аргументы успешно загружены.
2021-11-02 19:31:52,710 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2021-11-02 19:32:51,757 DEBUG decos.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2021-11-02 19:32:51,758 DEBUG decos.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2021-11-02 19:32:51,758 DEBUG decos.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2021-11-02 19:32:51,758 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['C:/Users/Максар/Desktop/geekbrains/PYQT/project/server.py']
2021-11-02 19:32:51,759 DEBUG server.py Аргументы успешно загружены.
2021-11-02 19:32:51,844 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2021-11-02 19:34:02,998 DEBUG decos.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2021-11-02 19:34:02,998 DEBUG decos.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2021-11-02 19:34:02,999 DEBUG decos.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2021-11-02 19:34:02,999 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['C:/Users/Максар/Desktop/geekbrains/PYQT/project/server.py']
2021-11-02 19:34:03,000 DEBUG server.py Аргументы успешно загружены.
2021-11-02 19:34:03,076 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2021-11-02 19:39:09,872 DEBUG decos.py Была вызвана функция main c параметрами () , {}. Вызов из модуля __main__
2021-11-02 19:39:09,872 DEBUG decos.py Была вызвана функция config_load c параметрами () , {}. Вызов из модуля __main__
2021-11-02 19:39:09,872 DEBUG decos.py Была вызвана функция arg_parser c параметрами ('7777', '') , {}. Вызов из модуля __main__
2021-11-02 19:39:09,872 DEBUG server.py Инициализация парсера аргументов коммандной строки: ['C:/Users/Максар/Desktop/geekbrains/PYQT/project/server.py']
2021-11-02 19:39:09,873 DEBUG server.py Аргументы успешно загружены.
2021-11-02 19:39:09,956 INFO core.py Запущен сервер, порт для подключений: 7777 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2021-11-02 19:45:27,911 INFO core.py Установлено соедение с ПК ('127.0.0.1', 59909)
2021-11-02 19:45:28,423 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1712, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59909)>,) , {}. Вызов из модуля common.utils
2021-11-02 19:45:28,424 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1635871527.9215522, 'user': {'account_name': 'alex', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0wLKK8wBprkXujH9Up2w\nVNIeI4Z8wOMT8rIGrjEUIm4wAT9E8YHOnIlQTltgEi4NSVwUNiTzjbatZVA2FOwk\nEIsyZNhbIKE/XmZ4YQuXsql+B9elPqmns0UbtHGedbio4nnNcE52sxdFv8ThgvR6\npnwFB69EEwUqsJSh2aaTMHb971oy7r+6B4/S9hb9FnNTmc1FN44MaXJI8h9vlLh8\nCPbvtSQDOSgTDulrsOGg/bcHvjxUEnwbvDmtjtIDhu4o/xOpBnQldPyO05nl84GP\n0MxkiiHg1g/7Iue0+SmryjDPhDWRcLVKxsNTsMCO1ynn3yKp55dx1dDyeaEwVJNI\nSQIDAQAB\n-----END PUBLIC KEY-----'}}
2021-11-02 19:45:28,424 DEBUG core.py Start auth process for {'account_name': 'alex', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0wLKK8wBprkXujH9Up2w\nVNIeI4Z8wOMT8rIGrjEUIm4wAT9E8YHOnIlQTltgEi4NSVwUNiTzjbatZVA2FOwk\nEIsyZNhbIKE/XmZ4YQuXsql+B9elPqmns0UbtHGedbio4nnNcE52sxdFv8ThgvR6\npnwFB69EEwUqsJSh2aaTMHb971oy7r+6B4/S9hb9FnNTmc1FN44MaXJI8h9vlLh8\nCPbvtSQDOSgTDulrsOGg/bcHvjxUEnwbvDmtjtIDhu4o/xOpBnQldPyO05nl84GP\n0MxkiiHg1g/7Iue0+SmryjDPhDWRcLVKxsNTsMCO1ynn3yKp55dx1dDyeaEwVJNI\nSQIDAQAB\n-----END PUBLIC KEY-----'}
2021-11-02 19:45:28,426 DEBUG core.py Correct username, starting passwd check.
2021-11-02 19:45:28,469 DEBUG core.py Auth message = {'response': 511, 'bin': '8c6df9a6419a09b691b170d23d3d11f1a0d35e287994d64fef78b04e4932ddda8df68266c8e39794bbde983653e10f2719f8395d3e76d33f743334faecfa05c0'}
2021-11-02 19:45:28,470 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=1712, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59909)>, {'response': 511, 'bin': '8c6df9a6419a09b691b170d23d3d11f1a0d35e287994d64fef78b04e4932ddda8df68266c8e39794bbde983653e10f2719f8395d3e76d33f743334faecfa05c0'}) , {}. Вызов из модуля common.utils
2021-11-02 19:45:28,470 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1712, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59909)>,) , {}. Вызов из модуля common.utils
2021-11-02 19:45:28,471 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=1712, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59909)>, {'response': 200}) , {}. Вызов из модуля common.utils
2021-11-02 19:45:29,002 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1712, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59909)>,) , {}. Вызов из модуля common.utils
2021-11-02 19:45:29,002 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1635871528.4723465, 'account_name': 'alex'}
2021-11-02 19:45:29,011 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=1712, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59909)>, {'response': 202, 'data_list': ['alex']}) , {}. Вызов из модуля common.utils
2021-11-02 19:45:29,526 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1712, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59909)>,) , {}. Вызов из модуля common.utils
2021-11-02 19:45:29,526 DEBUG core.py Getting data from client exception.
Traceback (most recent call last):
  File "C:\Users\Максар\Desktop\geekbrains\PYQT\project\server\core.py", line 86, in run
    get_message(client_with_message), client_with_message)
  File "C:\Users\Максар\Desktop\geekbrains\PYQT\project\common\decos.py", line 19, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "C:\Users\Максар\Desktop\geekbrains\PYQT\project\common\utils.py", line 25, in get_message
    response = json.loads(json_response)
  File "C:\Users\Максар\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Максар\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Максар\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-11-02 19:45:29,612 INFO core.py Клиент ('127.0.0.1', 59909) отключился от сервера.
2021-11-02 19:46:15,300 INFO core.py Установлено соедение с ПК ('127.0.0.1', 59910)
2021-11-02 19:46:15,808 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1644, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59910)>,) , {}. Вызов из модуля common.utils
2021-11-02 19:46:15,809 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1635871575.310983, 'user': {'account_name': 'alex', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0wLKK8wBprkXujH9Up2w\nVNIeI4Z8wOMT8rIGrjEUIm4wAT9E8YHOnIlQTltgEi4NSVwUNiTzjbatZVA2FOwk\nEIsyZNhbIKE/XmZ4YQuXsql+B9elPqmns0UbtHGedbio4nnNcE52sxdFv8ThgvR6\npnwFB69EEwUqsJSh2aaTMHb971oy7r+6B4/S9hb9FnNTmc1FN44MaXJI8h9vlLh8\nCPbvtSQDOSgTDulrsOGg/bcHvjxUEnwbvDmtjtIDhu4o/xOpBnQldPyO05nl84GP\n0MxkiiHg1g/7Iue0+SmryjDPhDWRcLVKxsNTsMCO1ynn3yKp55dx1dDyeaEwVJNI\nSQIDAQAB\n-----END PUBLIC KEY-----'}}
2021-11-02 19:46:15,809 DEBUG core.py Start auth process for {'account_name': 'alex', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0wLKK8wBprkXujH9Up2w\nVNIeI4Z8wOMT8rIGrjEUIm4wAT9E8YHOnIlQTltgEi4NSVwUNiTzjbatZVA2FOwk\nEIsyZNhbIKE/XmZ4YQuXsql+B9elPqmns0UbtHGedbio4nnNcE52sxdFv8ThgvR6\npnwFB69EEwUqsJSh2aaTMHb971oy7r+6B4/S9hb9FnNTmc1FN44MaXJI8h9vlLh8\nCPbvtSQDOSgTDulrsOGg/bcHvjxUEnwbvDmtjtIDhu4o/xOpBnQldPyO05nl84GP\n0MxkiiHg1g/7Iue0+SmryjDPhDWRcLVKxsNTsMCO1ynn3yKp55dx1dDyeaEwVJNI\nSQIDAQAB\n-----END PUBLIC KEY-----'}
2021-11-02 19:46:15,812 DEBUG core.py Correct username, starting passwd check.
2021-11-02 19:46:15,813 DEBUG core.py Auth message = {'response': 511, 'bin': '3bcda68594e3ed6dfead615c8b1f3046de89d25ef24e245a1a4c7925ffc5a5da9149aed0149c1036159798d98a0ec8b0c71f02be759aa352b87ce26d91dcf985'}
2021-11-02 19:46:15,814 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=1644, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59910)>, {'response': 511, 'bin': '3bcda68594e3ed6dfead615c8b1f3046de89d25ef24e245a1a4c7925ffc5a5da9149aed0149c1036159798d98a0ec8b0c71f02be759aa352b87ce26d91dcf985'}) , {}. Вызов из модуля common.utils
2021-11-02 19:46:15,814 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1644, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59910)>,) , {}. Вызов из модуля common.utils
2021-11-02 19:46:15,815 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=1644, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59910)>, {'response': 200}) , {}. Вызов из модуля common.utils
2021-11-02 19:46:16,352 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1644, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59910)>,) , {}. Вызов из модуля common.utils
2021-11-02 19:46:16,352 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1635871575.8152025, 'account_name': 'alex'}
2021-11-02 19:46:16,353 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=1644, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59910)>, {'response': 202, 'data_list': ['alex']}) , {}. Вызов из модуля common.utils
2021-11-02 19:46:16,853 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1644, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59910)>,) , {}. Вызов из модуля common.utils
2021-11-02 19:46:16,853 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1635871576.410283, 'user': 'alex'}
2021-11-02 19:46:16,858 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=1644, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59910)>, {'response': 202, 'data_list': []}) , {}. Вызов из модуля common.utils
2021-11-02 19:46:17,370 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1644, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59910)>,) , {}. Вызов из модуля common.utils
2021-11-02 19:46:17,370 DEBUG core.py Getting data from client exception.
Traceback (most recent call last):
  File "C:\Users\Максар\Desktop\geekbrains\PYQT\project\server\core.py", line 86, in run
    get_message(client_with_message), client_with_message)
  File "C:\Users\Максар\Desktop\geekbrains\PYQT\project\common\decos.py", line 19, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "C:\Users\Максар\Desktop\geekbrains\PYQT\project\common\utils.py", line 22, in get_message
    encoded_response = client.recv(MAX_PACKAGE_LENGTH)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2021-11-02 19:46:17,371 INFO core.py Клиент ('127.0.0.1', 59910) отключился от сервера.
2021-11-02 19:47:43,088 INFO core.py Установлено соедение с ПК ('127.0.0.1', 59921)
2021-11-02 19:47:43,602 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1712, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59921)>,) , {}. Вызов из модуля common.utils
2021-11-02 19:47:43,602 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1635871663.0980134, 'user': {'account_name': 'alex', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0wLKK8wBprkXujH9Up2w\nVNIeI4Z8wOMT8rIGrjEUIm4wAT9E8YHOnIlQTltgEi4NSVwUNiTzjbatZVA2FOwk\nEIsyZNhbIKE/XmZ4YQuXsql+B9elPqmns0UbtHGedbio4nnNcE52sxdFv8ThgvR6\npnwFB69EEwUqsJSh2aaTMHb971oy7r+6B4/S9hb9FnNTmc1FN44MaXJI8h9vlLh8\nCPbvtSQDOSgTDulrsOGg/bcHvjxUEnwbvDmtjtIDhu4o/xOpBnQldPyO05nl84GP\n0MxkiiHg1g/7Iue0+SmryjDPhDWRcLVKxsNTsMCO1ynn3yKp55dx1dDyeaEwVJNI\nSQIDAQAB\n-----END PUBLIC KEY-----'}}
2021-11-02 19:47:43,602 DEBUG core.py Start auth process for {'account_name': 'alex', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0wLKK8wBprkXujH9Up2w\nVNIeI4Z8wOMT8rIGrjEUIm4wAT9E8YHOnIlQTltgEi4NSVwUNiTzjbatZVA2FOwk\nEIsyZNhbIKE/XmZ4YQuXsql+B9elPqmns0UbtHGedbio4nnNcE52sxdFv8ThgvR6\npnwFB69EEwUqsJSh2aaTMHb971oy7r+6B4/S9hb9FnNTmc1FN44MaXJI8h9vlLh8\nCPbvtSQDOSgTDulrsOGg/bcHvjxUEnwbvDmtjtIDhu4o/xOpBnQldPyO05nl84GP\n0MxkiiHg1g/7Iue0+SmryjDPhDWRcLVKxsNTsMCO1ynn3yKp55dx1dDyeaEwVJNI\nSQIDAQAB\n-----END PUBLIC KEY-----'}
2021-11-02 19:47:43,604 DEBUG core.py Correct username, starting passwd check.
2021-11-02 19:47:43,604 DEBUG core.py Auth message = {'response': 511, 'bin': 'f03f269dad7ace6e9781efdc19b84eafb250c1aeeceb5684030b6ef634176d1a62c623dfce7ad11f72c31ee5a34502d72a580beeed8e4c2712fa5eb1068c6f1a'}
2021-11-02 19:47:43,605 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=1712, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59921)>, {'response': 511, 'bin': 'f03f269dad7ace6e9781efdc19b84eafb250c1aeeceb5684030b6ef634176d1a62c623dfce7ad11f72c31ee5a34502d72a580beeed8e4c2712fa5eb1068c6f1a'}) , {}. Вызов из модуля common.utils
2021-11-02 19:47:43,605 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1712, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59921)>,) , {}. Вызов из модуля common.utils
2021-11-02 19:47:43,605 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=1712, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59921)>, {'response': 200}) , {}. Вызов из модуля common.utils
2021-11-02 19:47:44,184 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1712, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59921)>,) , {}. Вызов из модуля common.utils
2021-11-02 19:47:44,184 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1635871663.6065264, 'account_name': 'alex'}
2021-11-02 19:47:44,185 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=1712, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59921)>, {'response': 202, 'data_list': ['alex']}) , {}. Вызов из модуля common.utils
2021-11-02 19:47:44,689 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1712, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59921)>,) , {}. Вызов из модуля common.utils
2021-11-02 19:47:44,690 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1635871664.2495224, 'user': 'alex'}
2021-11-02 19:47:44,695 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=1712, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59921)>, {'response': 202, 'data_list': []}) , {}. Вызов из модуля common.utils
2021-11-02 19:47:51,799 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1712, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59921)>,) , {}. Вызов из модуля common.utils
2021-11-02 19:47:51,799 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1635871671.7538278, 'account_name': 'alex'}
2021-11-02 19:47:51,800 INFO core.py Клиент ('127.0.0.1', 59921) отключился от сервера.
2021-11-02 19:48:36,516 INFO core.py Установлено соедение с ПК ('127.0.0.1', 59925)
2021-11-02 19:48:37,020 DEBUG decos.py Была вызвана функция get_message c параметрами (<socket.socket fd=1712, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59925)>,) , {}. Вызов из модуля common.utils
2021-11-02 19:48:37,021 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1635871716.5264628, 'user': {'account_name': 'ALex1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAha2DlyOtEAGAFcEmxnT7\n6addHl1gF/MEkeQYcvZf3t2D/LAEeDUCW4vTYHLV/qHFcUfLhkdB6HVXHhMfE/rU\nlwVPzZFtwNU8SFLlsJ5DamGlFNWMPZpc7K2YBFLdEBgE1kaHj531l8NakRSITJDZ\nBpRP3rGjfZivVXjszCZle1aBBJM+PpLH+40+iYyQRttQQpPbDq+SvvvolvFMP/Oi\nyAUPCsjA9fPl5hu0wiPW0Oa7Cg3vpk4GUUMHqwHzFS2ZCn2cT4FzyTbw21RkmbPM\ncTSGIfQq0vyc+YVTtV469f6jXOStJVDC0NxIXFURtCE9BpfJ7+SNTLFs6GaOeWqZ\nywIDAQAB\n-----END PUBLIC KEY-----'}}
2021-11-02 19:48:37,021 DEBUG core.py Start auth process for {'account_name': 'ALex1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAha2DlyOtEAGAFcEmxnT7\n6addHl1gF/MEkeQYcvZf3t2D/LAEeDUCW4vTYHLV/qHFcUfLhkdB6HVXHhMfE/rU\nlwVPzZFtwNU8SFLlsJ5DamGlFNWMPZpc7K2YBFLdEBgE1kaHj531l8NakRSITJDZ\nBpRP3rGjfZivVXjszCZle1aBBJM+PpLH+40+iYyQRttQQpPbDq+SvvvolvFMP/Oi\nyAUPCsjA9fPl5hu0wiPW0Oa7Cg3vpk4GUUMHqwHzFS2ZCn2cT4FzyTbw21RkmbPM\ncTSGIfQq0vyc+YVTtV469f6jXOStJVDC0NxIXFURtCE9BpfJ7+SNTLFs6GaOeWqZ\nywIDAQAB\n-----END PUBLIC KEY-----'}
2021-11-02 19:48:37,025 DEBUG core.py Unknown username, sending {'response': 400, 'error': 'Пользователь не зарегистрирован.'}
2021-11-02 19:48:37,026 DEBUG decos.py Была вызвана функция send_message c параметрами (<socket.socket fd=1712, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 59925)>, {'response': 400, 'error': 'Пользователь не зарегистрирован.'}) , {}. Вызов из модуля common.utils
